name: Wireguard setup
author: nastradamus39
description: Install and setup vpn via wireguard.

inputs:
  client_config:
    description: client vpn config
    required: true
    default: false

runs:
  using: "composite"

  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Setup wireguard
      run: |
        sudo apt install wireguard resolvconf iptables
        echo "${{ inputs.client_config }}" > ~/wg0.conf
        sudo mv ~/wg0.conf /etc/wireguard/wg0.conf
        sudo wg-quick up wg0

      shell: bash
