name: Wireguard setup
author: nastradamus39
description: Install and setup vpn via wireguard.

inputs:
  client_config:
    description: client vpn config
    required: true
    default: false

runs:
  using: "composite"

  steps:
    - name: Setup wireguard

    - run: sudo apt install wireguard resolvconf iptables

    - run: echo "${{ secrets.WG_CONF }}" > ~/wg0.conf

    - run: sudo mv ~/wg0.conf /etc/wireguard/wg0.conf

    - run: sudo wg-quick up wg0
